version: '3.8'
services:
  seo-nginx:
    image: nginx:alpine
    container_name: seo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../seo-pages:/var/www/connecteurs:ro
      - ./nginx/seo-active-conf:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
