server {
    listen 80;
    server_name shopify-odoo.shopconnect.fr;
    root /var/www/connecteurs/shopify-odoo.shopconnect.fr;
    index index.html;
    charset utf-8;

    # Certbot webroot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri /index.html =404;
    }

    location ~* \.(html|css|js|ico|png|jpg|svg)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
